### ISSUE TITLE
Runtime Error in `personalized_retriever/train_retriever.py`

### ISSUE THREAD

**Issue by Nana2929** [zhouhanxie/PRAG#2]
Thank you for the great work and opensourcing!
In the attempt to reproduce, I encountered a runtime error and am not able to figure out how to solve it. Pardon me for writing this lengthy issue, but I believe adding details and my debugging footsteps help. Could you please try to pinpoint what went wrong? Big thank you. 
## Command
```
py personalized_retriever/train_retriever.py --auto_arg_by_dataset=yelp --use_user_topic  
```
- I slightly altered the argument interface as follows (changes under `if __name__ == '__main__':` are attached):
 
```python3 
# personalized_retriever/train_retriever.py
... 
if __name__ == '__main__':
    import argparse
    from typing import Final

    from easydict import EasyDict as edict


    parser = argparse.ArgumentParser(description='Personalized Retriever model')
    parser.add_argument('--auto_arg_by_dataset', type=str, default=None,
                        help='auto argument')
    parser.add_argument('--use_user_topic', action='store_true',
                        help='use user topic')
    out_main_dir: Final = 'user_topic' if parser.parse_args().use_user_topic else 'item_topic'
    args = parser.parse_args()
    # parser.add_argument('--data_path', type=str, default=None,
    #                     help='path for loading the pickle data')
    # parser.add_argument('--index_dir', type=str, default=None,
    #                     help='load indexes')
    # parser.add_argument('--cached_review_embedding', type=str, default=None,
    #                     help='place to try to load/save cached_review_embedding')
    # parser.add_argument('--output_dir', type=str, default='./tmp_output',
    #                     help='place to save essentially everything, args, weight, etc.')
    train_args = edict(
        epochs=50,
        lr = 5e-5,
        save_total_limit=1,
        per_device_train_batch_size=128,
        per_device_eval_batch_size=256,
        gradient_accumulation_steps=1,
        log_interval=500,
        tolerance_steps=3,
        ui_hidden_size=32,
        num_latent_factor=5,
        bert_intermediate_size=768,
        bert_num_hidden_layers=1,
        bert_num_attention_heads=1,
        use_wide=True,
        sentence_transformer_name='all-mpnet-base-v2',
        use_user_topic=args.use_user_topic,
        force_document_embeddings_on_cpu=True,
    )

    if args.auto_arg_by_dataset is not None:

        assert args.auto_arg_by_dataset in ('yelp', 'movies_and_tv', 'tripadvisor')
        if args.auto_arg_by_dataset == 'tripadvisor':
            args = edict(
                dict(
                    data_path = '../nlg4rec_data/TripAdvisor/reviews.pickle',
                    index_dir = '../nlg4rec_data/TripAdvisor/1',
                    cached_review_embedding = 'archive/transformer_retriever/tripadvisor_table.npy',
                    output_dir = f'personalized_retriever/mpnet_space/{out_main_dir}/TripAdvisor/1',
                )
            )
        elif args.auto_arg_by_dataset == 'yelp':
            args = edict(
                dict(
                    data_path = '../nlg4rec_data/Yelp/reviews.pickle',
                    index_dir = '../nlg4rec_data/Yelp/1',
                    cached_review_embedding = 'archive/transformer_retriever/yelp_table.npy',
                    output_dir = f'personalized_retriever/mpnet_space/{out_main_dir}/Yelp/1',
                )
            )
        elif args.auto_arg_by_dataset == 'movies_and_tv':
            args = edict(
                dict(
                    data_path = '../nlg4rec_data/Movies_and_TV/reviews.pickle',
                    index_dir = '../nlg4rec_data/Movies_and_TV/1',
                    cached_review_embedding = 'archive/transformer_retriever/movies_table.npy',
                    output_dir = f'personalized_retriever/mpnet_space/{out_main_dir}/Movies_and_TV/1',
                )
            )
    # args = args + train_args
    args.update(train_args)
    print('args: ', args)
    best_model, review_history = main(args)
    eval_on_test(best_model, review_history, args)
```

## What's the expected result?

- Model forwards successfully. 

## What's the actual result?

- An error happens during model forwarding (traceback). 
```
Traceback (most recent call last):                                                                                                                                                 
  File "/home/P76114511/projects/PRAG/personalized_retriever/train_retriever.py", line 291, in <module>                                                                            
    best_model, review_history = main(args) 
    ...
    
    
  File "/home/P76114511/projects/PRAG/personalized_retriever/modeling_bertwithoutpositionembedding.py", line 146, in forward
    embeddings = embeddings + next_emb
RuntimeError: The size of tensor a (768) must match the size of tensor b (32) at non-singleton dimension 2
```

### Package Versions
```
>>> import torch, transformers
>>> torch.__version__
'2.1.2+cu121'
>>> transformers.__version__
'4.33.1'
```
### Tracing
The error occurred here, 
```python 
#/home/P76114511/projects/PRAG/personalized_retriever/modeling_bertwithoutpositionembedding.py
while len(self.additive_embeddings) > 0:
            next_emb = self.additive_embeddings.pop()
            embeddings = embeddings + next_emb

        return embeddings

```
So I tried to search for the places where `additive_embeddings` appear. I spotted `PersonalizedRetrieverModel` has 2 lines in its `forward()` function. 
```python3
self.bert.embeddings.additive_embeddings.append(
            self.ui_embedding_table.get_user_embedding(user).unsqueeze(-2).repeat(1, review_history_input_ids.shape[1], 1)
        )
self.bert.embeddings.additive_embeddings.append(
            self.ui_embedding_table.get_item_embedding(item).unsqueeze(-2).repeat(1, review_history_input_ids.shape[1], 1)
        )
```
Since there involves some complex tensor manipulation, I tried checking all their shapes:
- `self.ui_embedding_table.get_user_embedding(user)`: torch.Size([128, 32])     # (batch_size, ui_hidden_dim)
- `review_history_input_ids`: torch.Size([128, 1113])  # (batch_size, history_length)
- `self.ui_embedding_table.get_user_embedding(user).unsqueeze(-2).repeat(1, 1113, 1)`: torch.Size([128, 1113, 32])    # (batch_size, history_length, ui_hidden_dim)     
- `embeddings`: torch.Size([128, 1113, 768])   # (batch_size, history_length, bert_hidden_dim)

Supposedly, the `self.ui_embedding_table.get_user_embedding(user).unsqueeze(-2).repeat(1, 1113, 1)` and `embeddings` should be able to be added, and I do not understand why **there's a mismatch in the final dimension**. I suspect that this part corresponds to your paper's `Review Aggregation` $v_u +v_i +c$, if this is the case then everything should be in the same dimension $d$, so one of`32` and `768` may be wrong. 

![image](https://github.com/zhouhanxie/PRAG/assets/58811089/94a9ceb3-d270-4837-945d-901758925c5a)

**Comment by Nana2929** [comment]
According to your `embedding_interpreter` entry point, it looks like choosing `ui_hidden_size` = 768 could be the right way to solve this.

**Comment by zhouhanxie** [comment]
Yeah good catch, thanks! I think 768 is the way to go....
LMN if this causes any further issue - closing this for now but do ping again if needed.
